# Generated by Django 6.0.7 on 2026-08-04 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('chat', 'Chat'), ('generation', 'Generation'), ('evaluation', 'Evaluation')], max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('prompt_tokens', models.PositiveIntegerField()),
                ('completion_tokens', models.PositiveIntegerField()),
                ('reasoning_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
