# Generated by Django 6.0.7 on 2026-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlog',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
