# Generated by Django 6.0.7 on 2026-07-28 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('atomic_qa', 'Atomic Q&A'), ('atomic_cloze', 'Atomic Cloze'), ('synthesis', 'Synthesis')], max_length=20)),
                ('question', models.TextField()),
                ('key_points', models.JSONField(default=list)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('interval_index', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('dormant', 'Dormant')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='notions.notion')),
            ],
            options={
                'ordering': ['next_review_at'],
            },
        ),
    ]
